In [121]:
import pandas as pd
import re

pd.set_option("display.max_colwidth", None)

In [122]:
data_path = "../data/raw/home_depot_data_1_2021_12.csv"

In [123]:
df = pd.read_csv(data_path)

In [124]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2551 entries, 0 to 2550
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         2551 non-null   int64
 1   url           2551 non-null   str
 2   title         2551 non-null   str
 3   images        2551 non-null   str
 4   description   2551 non-null   str
 5   product_id    2551 non-null   int64
 6   sku           2407 non-null   float64
 7   gtin13        2170 non-null   float64
 8   brand         2551 non-null   str
 9   price         2551 non-null   float64
 10  currency      2551 non-null   str
 11  availability  2551 non-null   str
 12  uniq_id       2551 non-null   str
 13  scraped_at    2551 non-null   str
dtypes: float64(3), int64(2), str(9)
memory usage: 279.1 KB

In [125]:
select_cols = ['title', 'description', 'brand']

In [126]:
df[select_cols].head(10)

,title,description,brand
0,Men's 3X Large Carbon Heather Cotton/Polyester Rain Defender Paxton Heavyweight Hooded Zip-Front Sweatshirt,"This heavyweight, water-repellent hooded sweatshirt has a zip front for fast layering. ORIGINAL FIT. 13 oz., 75% cotton/25% polyester blend with Rain Defender durable water repellent. Attached, jersey-lined three-piece hood with drawcord closure. Antique-finish brass front zipper. Two front hand-warmer pockets have a hidden security pocket inside. Stretchable, spandex-reinforced rib-knit cuffs and waistband. Locker loop facilitates hanging.",Carhartt
1,Turmode 30 ft. RP TNC Female to RP TNC Male Adapter Cable,"If you need more length between your existing wireless device and Hi-Gain Antenna, this is the product for you. It's compatible with most Wi-Fi Antennas, so it is easy for you to extend your wireless network. Just replace your existing cable that runs between your wireless device and Antenna and you're ready to use your network with extended range.",Unbranded
2,Large Tapestry Bolster Bed,"Polyester cover resembling rich Italian tapestries wraps your pet in comfort and style. 100% recycled polyester high loft MemoryFiber fill keeps pets elevated off cold floors for relief on tired joints and pressure points. A great fit for pets up to 100 lbs. Zippered removable cover is machine washable in cold water only. To dry, use a delicate cycle or gentle setting with very low heat.",Carolina Pet Company
3,16-Gauge-Sinks Vessel Sink in White with Faucet,It features a rectangle shape. This vessel set is designed to be installed as a undermount vessel set. It is constructed with ceramic. This vessel set comes with an enamel glaze finish in White color. It is designed for a deck mount faucet.,Unbranded
4,Men's Crazy Horse 9'' Logger Boot - Steel Toe - Black Size 10.5(W),This 9 in. black full grain leather logger boot is Tough. With plain soft toe and rubber outsole it provides dependable traction with a comfortable fit. It is made with Goodyear Welt Construction so it is sturdy and secure.,Adtec
5,Mariana 6 ft. Multi-Color 3-Panel Screen Divider,"With robust structure and sophisticated canvas printing, this 3-panel screen is colorfully designed to be a great way to carve out space in your room or anywhere around the home. Not only will this elegant piece give you the needed exclusivity but it will also add inspiring style and beauty to your decor. This screen creatively features canvas print of a different and complementary images on each side. With its lightweight construction, our screen will definitely fill your space with inspiring visual flair for many-Years to come. 3-panel screen finished on both sides Canvas printing.",HomeRoots
6,5 gal. #650C-2 Powdery Mist Semi-Gloss Interior Paint,"BEHR PRO i300 Semi-Gloss Interior Paint has a sleek, radiant sheen appearance. This professional quality latex paint has superior hide and coverage, excellent sprayability, spray and back-roll, and superior touch-up. Use on properly prepared and primed drywall, concrete, masonry, wood and metal surfaces in both residential and commercial applications.",BEHR PRO
7,7/8 in. x 4-1/2 in. x 0.045 in. Metal and Stainless Cutting Wheel (50-Pack),DEWALT High Performance 0.045 in. Metal Cutting Wheels have a thin 0.045 in. cutting edge design for fast burr free cutting. They have a proprietary aluminum oxide grain combination for aggressive cutting action and the proprietary material mix ensures durable long life wheels. They have 2-full sheets of fiberglass for durability and user safety. These wheels are ideal for high performance cutting in all types of ferrous metals and stainless steel.,DEWALT
8,Ring Gold Bar Cart,This Ring Bar Cart is sure to make a statement in any room. This carts features a metal frame in gold and the two shelves are made of mirror with an antique finish. We offer a wide variety of furniture and decorative accessories to meet all of your decor needs.,Titan Lighting
9,Traditional Silver Wooden Vanity Table,This transitional vanity table proudly displays gently curved legs that help draw attention to the carved details on the drawer panels. Spread out your makeup and beauty products across the two shelves or in the multiple drawers so everything is in one place. It enhances the beauty of the room.,Benjara

In [127]:
df_search = df[select_cols]

In [128]:
df_search['combined_text'] = df_search['title'].fillna('') + ' ' + df_search['description'].fillna('')

## Clean data

The EDA analysis show that we need to perform the following cleaning steps:

- Remove non-ascii characters
- Remove special characters
- Lowercase text

In [129]:
def remove_non_ascii(text: str) -> str:
    if isinstance(text, str):
        return ''.join(char for char in text if ord(char) < 128)
    return text

In [130]:
def remove_special_characters(text: str) -> str:
    if isinstance(text, str):
        return ''.join(char for char in text if char.isalnum() or char.isspace())
    return text

In [131]:
def lowercase_text(text: str) -> str:
    if isinstance(text, str):
        return text.lower()
    return text

In [132]:
cleaning_steps = [
    remove_non_ascii,
    remove_special_characters,
    lowercase_text
]

result = df_search['combined_text'].copy()
for func in cleaning_steps:
    result = result.apply(func)
df_search['combined_text_clean'] = result

In [133]:
df_search.head()

,title,description,brand,combined_text,combined_text_clean
0,Men's 3X Large Carbon Heather Cotton/Polyester Rain Defender Paxton Heavyweight Hooded Zip-Front Sweatshirt,"This heavyweight, water-repellent hooded sweatshirt has a zip front for fast layering. ORIGINAL FIT. 13 oz., 75% cotton/25% polyester blend with Rain Defender durable water repellent. Attached, jersey-lined three-piece hood with drawcord closure. Antique-finish brass front zipper. Two front hand-warmer pockets have a hidden security pocket inside. Stretchable, spandex-reinforced rib-knit cuffs and waistband. Locker loop facilitates hanging.",Carhartt,"Men's 3X Large Carbon Heather Cotton/Polyester Rain Defender Paxton Heavyweight Hooded Zip-Front Sweatshirt This heavyweight, water-repellent hooded sweatshirt has a zip front for fast layering. ORIGINAL FIT. 13 oz., 75% cotton/25% polyester blend with Rain Defender durable water repellent. Attached, jersey-lined three-piece hood with drawcord closure. Antique-finish brass front zipper. Two front hand-warmer pockets have a hidden security pocket inside. Stretchable, spandex-reinforced rib-knit cuffs and waistband. Locker loop facilitates hanging.",mens 3x large carbon heather cottonpolyester rain defender paxton heavyweight hooded zipfront sweatshirt this heavyweight waterrepellent hooded sweatshirt has a zip front for fast layering original fit 13 oz 75 cotton25 polyester blend with rain defender durable water repellent attached jerseylined threepiece hood with drawcord closure antiquefinish brass front zipper two front handwarmer pockets have a hidden security pocket inside stretchable spandexreinforced ribknit cuffs and waistband locker loop facilitates hanging
1,Turmode 30 ft. RP TNC Female to RP TNC Male Adapter Cable,"If you need more length between your existing wireless device and Hi-Gain Antenna, this is the product for you. It's compatible with most Wi-Fi Antennas, so it is easy for you to extend your wireless network. Just replace your existing cable that runs between your wireless device and Antenna and you're ready to use your network with extended range.",Unbranded,"Turmode 30 ft. RP TNC Female to RP TNC Male Adapter Cable If you need more length between your existing wireless device and Hi-Gain Antenna, this is the product for you. It's compatible with most Wi-Fi Antennas, so it is easy for you to extend your wireless network. Just replace your existing cable that runs between your wireless device and Antenna and you're ready to use your network with extended range.",turmode 30 ft rp tnc female to rp tnc male adapter cable if you need more length between your existing wireless device and higain antenna this is the product for you its compatible with most wifi antennas so it is easy for you to extend your wireless network just replace your existing cable that runs between your wireless device and antenna and youre ready to use your network with extended range
2,Large Tapestry Bolster Bed,"Polyester cover resembling rich Italian tapestries wraps your pet in comfort and style. 100% recycled polyester high loft MemoryFiber fill keeps pets elevated off cold floors for relief on tired joints and pressure points. A great fit for pets up to 100 lbs. Zippered removable cover is machine washable in cold water only. To dry, use a delicate cycle or gentle setting with very low heat.",Carolina Pet Company,"Large Tapestry Bolster Bed Polyester cover resembling rich Italian tapestries wraps your pet in comfort and style. 100% recycled polyester high loft MemoryFiber fill keeps pets elevated off cold floors for relief on tired joints and pressure points. A great fit for pets up to 100 lbs. Zippered removable cover is machine washable in cold water only. To dry, use a delicate cycle or gentle setting with very low heat.",large tapestry bolster bed polyester cover resembling rich italian tapestries wraps your pet in comfort and style 100 recycled polyester high loft memoryfiber fill keeps pets elevated off cold floors for relief on tired joints and pressure points a great fit for pets up to 100 lbs zippered removable cover is machine washable in cold water only to dry use a delicate cycle or gentle setting with very low heat
3,16-Gauge-Sinks Vessel Sink in White with Faucet,It features a rectangle shape. This vessel set is designed to be installed as a undermount vessel set. It is constructed with ceramic. This vessel set comes with an enamel glaze finish in White color. It is designed for a deck mount faucet.,Unbranded,16-Gauge-Sinks Vessel Sink in White with Faucet It features a rectangle shape. This vessel set is designed to be installed as a undermount vessel set. It is constructed with ceramic. This vessel set comes with an enamel glaze finish in White color. It is designed for a deck mount faucet.,16gaugesinks vessel sink in white with faucet it features a rectangle shape this vessel set is designed to be installed as a undermount vessel set it is constructed with ceramic this vessel set comes with an enamel glaze finish in white color it is designed for a deck mount faucet
4,Men's Crazy Horse 9'' Logger Boot - Steel Toe - Black Size 10.5(W),This 9 in. black full grain leather logger boot is Tough. With plain soft toe and rubber outsole it provides dependable traction with a comfortable fit. It is made with Goodyear Welt Construction so it is sturdy and secure.,Adtec,Men's Crazy Horse 9'' Logger Boot - Steel Toe - Black Size 10.5(W) This 9 in. black full grain leather logger boot is Tough. With plain soft toe and rubber outsole it provides dependable traction with a comfortable fit. It is made with Goodyear Welt Construction so it is sturdy and secure.,mens crazy horse 9 logger boot steel toe black size 105w this 9 in black full grain leather logger boot is tough with plain soft toe and rubber outsole it provides dependable traction with a comfortable fit it is made with goodyear welt construction so it is sturdy and secure

## Sparse search engine

### Preprocessing text

Before creating BoW vectors, we need to preprocess the data.

In [134]:
def remove_stop_words(text: str) -> str:
    from nltk.corpus import stopwords
    stop_words = set(stopwords.words('english'))
    if isinstance(text, str):
        return ' '.join(word for word in text.split() if word not in stop_words)
    return text

In [135]:
def stemm_words(text: str) -> str:
    from nltk.stem import PorterStemmer
    stemmer = PorterStemmer()
    if isinstance(text, str):
        return ' '.join(stemmer.stem(word) for word in text.split())
    return text

In [136]:
preprocessing_steps = [
    remove_stop_words,
    stemm_words
]

result = df_search['combined_text_clean'].copy()
for func in preprocessing_steps:
    result = result.apply(func)
    
df_search['combined_text_clean_preprocessed'] = result

In [137]:
def get_sparse_vectorizer(df: pd.DataFrame, column_name: str):
    from sklearn.feature_extraction.text import TfidfVectorizer
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(df[column_name])
    return tfidf_matrix, vectorizer

In [138]:
tfidf_matrix, vectorizer = get_sparse_vectorizer(df_search, 'combined_text_clean')

In [148]:
from sklearn.metrics.pairwise import cosine_similarity

def search_engine(query, df, tfidf_matrix, vectorizer, top_n=5):
    # 1. Transform the user's query using the already fitted vectorizer
    query_vec = vectorizer.transform([query])
    
    # 2. Calculate cosine similarity between the query and all documents
    cosine_scores = cosine_similarity(query_vec, tfidf_matrix).flatten()
    
    # 3. Add the scores to a copy of the dataframe
    results_df = df.copy()
    results_df['similarity_score'] = cosine_scores
    
    # 4. Filter for documents that have a score greater than 0 (relevant matches)
    results_df = results_df[results_df['similarity_score'] > 0]
    
    # 5. Sort by similarity score in descending order
    results_df = results_df.sort_values(by='similarity_score', ascending=False)
    
    # 6. Return the top N results
    return results_df.head(top_n)

In [149]:
user_query = "steel toe work boots"

user_query_cleaned = user_query
for func in cleaning_steps:
    user_query_cleaned = func(user_query_cleaned)

for func in preprocessing_steps:
    user_query_preprocessed = func(user_query_cleaned)

print(f"User query preprocessed: '{user_query_preprocessed}'\n ")

User query preprocessed: 'steel toe work boot'

In [151]:
results = search_engine(user_query_preprocessed, df_search, tfidf_matrix, vectorizer)

print(f"Search results for: '{user_query_preprocessed}'\n")
for index, row in results.iterrows():
    print(f"Title: {row['title']}")
    print(f"Description: {row['description']}")
    print(f"Score: {row['similarity_score']:.4f}\n")

Search results for: 'steel toe work boot'

Title: Men's MobiLite Waterproof Oil-Resistant 8 in. Work Boot - Steel Toe - Brown - Size - 11(M)
Description: The ROCKY MobiLite Steel Toe Waterproof Oil-Resistant Work Boot offers 8 in. of footwear protection without compromising your capacity to move quickly and work productively. ROCKY carefully constructed a steel toe boot that meets ASTM F2413 protective toe classification and boasts the widest oblique toe box in the industry. You can carry on with the work you love, knowing accidents around you are no need to worry. ROCKY has you covered in this safety toe boot. The unique, oil-resistant 3-part MobiLite outsole, around which this work boot is based, provides exceptional grip to steady your stride without bogging down your mobility. The lightweight material lets you move at the pace you prefer, while adding safety to your every step. Guaranteed ROCKY Waterproof construction is the high-quality assurance you'll appreciate when confronting water in the workplace. From the moment you clock-in to the moment you clock-out, enjoy dry, comfortable feet in this men's waterproof boot. A work boot should offer as much comfort as it does security. The removable polyurethane footbed in this strategically crafted shoe will keep your feet relieved and your mood happy. If you're a hard-worker who wants a boot to match your ethic, the ROCKY MobiLite Steel Toe Waterproof Oil-Resistant Work Boot is your solution.
Score: 0.6063

Title: Men's Waterproof Logger Boot - Steel Toe - Chocolate Size 10(W)
Description: GEORGIA BOOT steel toe waterproof Logger boots will keep your feet safe and dry while providing comfort and durability day in and day out. Equipped with a steel toe, this boot meets ASTM standards for protective toe and electrical hazard. It features an abrasion-resistant scalloped heel rubber outsole and its made with the trusted Goodyear welt construction. Built with the Georgia Waterproof System, this logger stands up to rain, mud and everything in between. Air gets in, but water cant. 100% guaranteed. This also is a comfortable boot with a covered cushion insole and a fully-lined and cushioned collar. Support comes from a steel shank and a removable polyurethane orthotic insert. The brush guard kiltie is removable on this full-grain leather 8 in. boot. The men's logging boot also features solid stud hook and eyelets set on steel washers.
Score: 0.5263

Title: Men's Crazy Horse 9'' Logger Boot - Steel Toe - Black Size 10.5(W)
Description: This 9 in. black full grain leather logger boot is Tough. With plain soft toe and rubber outsole it provides dependable traction with a comfortable fit. It is made with Goodyear Welt Construction so it is sturdy and secure.
Score: 0.4030

Title: Men's Floorhand Waterproof Wellington Work Boots - Steel Toe - Brown Size 10.5(M)
Description: Wear a boot that's built to last with these Wolverine Floorhand Work Boots. ASTM- and EH-rated, they have a steel toe and a slip-resistant rubber outsole for all-day jobsite protection. The full-grain, waterproof leather upper and inside add style and comfort. A nylon shank gives them maximum support. The moisture wicking mesh lining keeps your feet cool and dry throughout the day.
Score: 0.3562

Title: Men's Size 13 Brown Barnyard PVC Boot
Description: Comfortable, yet heavy-duty for all outdoor work. Hard-working people deserve a boot that can stand up to everything that they do. Self-cleaning lug draft angles and rolled heel extension.
Score: 0.2650